name: parse_server_sdk
description: Dart plugin for Parse Server, (https://parseplatform.org), (https://back4app.com)
version: 2.1.0
homepage: https://github.com/phillwiggins/flutter_parse_sdk

environment:
  sdk: ">=2.12.0-29.10.beta <3.0.0"

dependencies:

  # Networking
  dio: ^4.0.0-beta2
  http: ^0.13.0
  web_socket_channel: ^2.0.0

  #Database
  sembast: ^3.0.0+1
  sembast_web: ^2.0.0
  xxtea: ^2.0.3

  # Utils
  uuid: ^3.0.0
  meta: ^1.3.0
  path: ^1.8.0
  mime_type: ^0.3.2

dev_dependencies:
  # Testing
  test: ^1.16.4
  mockito: ^5.0.0
